#!/bin/bash
#
# Start diaspora websocket and main services
#
realpath=$( python -c \
   "import os.path; print os.path.abspath(os.path.realpath(\"$0\"))")
cd $( dirname $realpath)/..

[ -e config/server.sh ] && source config/server.sh

THIN_ARGS="$DEFAULT_THIN_ARGS $@"
read -a args <<EOF
${THIN_ARGS:-'-h'}
EOF

for (( i = ${#args[*]} - 1; i >= 0; i--)); do
    if [ "${args[$i]}" = '-p' ]; then
        PORT="${args[ $(( i+1))]}"
        break
    fi
    shift
done

# Is someone listening on the ports already? (ipv4 only test ?)
services=$( netstat -nl | grep '[^:]:'$PORT'[ \t]')
if [ -n "$services" ]; then
    echo "Error: something is already using thin port $PORT. Exiting" >&2
    echo "     $services"
    exit 64
fi

services=$( netstat -nl | grep '[^:]:8080[ \t]')
if [ -n "$services" ]; then
    echo "Error: something is already using websocket port 8080. Exiting" >&2
    echo "     $services"
    exit 64
fi

# Check if Mongo is running
if  ! pgrep mongod >/dev/null
then
    echo "Error: Mongod not started. Exiting" >&2
    exit 64
fi

#force AGPL
if [ -w public  -a ! -e  public/source.tar ]; then
    tar czf public/source.tar.gz --exclude='source.tar.gz' -X .gitignore *
fi
if [ ! -e public/source.tar ]; then
    echo "Error: Can't find, or even create, public/source.tar. Exiting" >&2
    exit 65
fi

mkdir -p -v log/thin/
bundle exec ruby ./script/websocket_server.rb&
bundle exec thin start $THIN_ARGS
