#!/bin/bash
#
# Start diaspora websocket and main services
#

PORT=3000
THIN_ARGS=$@
while [ $(( $# > 1 )) = "1" ]; do
    if [ "$1" = '-p' ]; then
        PORT="$2";
        break
    fi
    shift
done

# Is someone listening on the ports already? (ipv4 only test ?)
services=$( netstat -nl | grep '[^:]:'$PORT'[ \t]')
if [ -n "$services" ]; then
    echo "Warning: something is already using thin port $PORT"
    echo "     $services"
    exit 1
fi

services=$( netstat -nl | grep '[^:]:8080[ \t]')
if [ -n "$services" ]; then
    echo "Warning: something is already using websocket port 8080"
    echo "     $services"
    exit 1
fi

# Check if Mongo is running
if  ! pgrep mongod >/dev/null
then
    echo "Mongod not started"
    exit 1
fi

#force AGPL
if [ -w public -a ! -e  public/source.tar ]; then
    tar czf public/source.tar.gz --exclude='source.tar.gz' -X .gitignore *
fi
if [ ! -e public/source.tar ]; then
    echo "Can't find, or even create, public/source.tar. Giving up"
    exit 2
fi

mkdir -p -v log/thin/
bundle exec ruby ./script/websocket_server.rb&
bundle exec thin start $THIN_ARGS

